include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    always_use_package_imports: ignore
    use_late_for_private_fields_and_variables: ignore
    avoid_catches_without_on_clauses: ignore

linter:
  rules:
    prefer_relative_imports: true
