name: tasque
description: "A new Flutter project."
publish_to: "none"
version: 0.0.4

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.5
  collection: ^1.19.1
  connectivity_plus: ^6.1.3
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flex_color_scheme: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.0.0
  form_builder_validators: ^11.1.2 # TODO: needed?
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  google_sign_in: ^6.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  timezone: ^0.10.0
  uuid: ^4.5.1
  wave: ^0.2.2

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  go_router_builder: ^2.8.2
  json_serializable: ^6.9.0
  objectbox_generator: ^4.1.0
  very_good_analysis: ^7.0.0

dependency_overrides:
  source_gen: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
